# src/predict.py

import joblib
import torch
import numpy as np
import pandas as pd
from src.ann_model import CreditANN
from config import RF_MODEL_FILE, XGB_MODEL_FILE, ANN_MODEL_FILE, PREPROCESSOR_FILE

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------- Loaders ---------------- #
def load_rf():
    return joblib.load(RF_MODEL_FILE)

def load_xgb():
    return joblib.load(XGB_MODEL_FILE)

def load_ann(input_dim):
    model = CreditANN(input_dim).to(device)
    model.load_state_dict(torch.load(ANN_MODEL_FILE, map_location=device))
    model.eval()
    return model

def load_preprocessor():
    return joblib.load(PREPROCESSOR_FILE)

# ---------------- Prediction Wrapper ---------------- #
def predict(model_type="rf", raw_input_dict=None):
    if raw_input_dict is None:
        raise ValueError("Provide input data as a dictionary")

    df_input = pd.DataFrame([raw_input_dict])
    preprocessor = load_preprocessor()
    X_transformed = preprocessor.transform(df_input)

    if model_type == "rf":
        model = load_rf()
        proba = model.predict_proba(X_transformed)[:, 1]
        pred = (proba > 0.5).astype(int)

    elif model_type == "xgb":
        model = load_xgb()
        proba = model.predict_proba(X_transformed)[:, 1]
        pred = (proba > 0.5).astype(int)

    elif model_type == "ann":
        X_dense = X_transformed.toarray() if hasattr(X_transformed, "toarray") else X_transformed
        model = load_ann(X_dense.shape[1])
        with torch.no_grad():
            inputs = torch.tensor(X_dense, dtype=torch.float32).to(device)
            output = torch.sigmoid(model(inputs)).cpu().numpy().flatten()
            proba = output
            pred = (proba > 0.5).astype(int)
    else:
        raise ValueError("Model type must be 'rf', 'xgb', or 'ann'.")

    return {"prediction": int(pred[0]), "probability": float(proba[0])}

# ---------------- Example ---------------- #
if __name__ == "__main__":
    # 👇 Replace with a real row from your dataset
    sample_input = {'SK_ID_CURR': 100002, 'NAME_CONTRACT_TYPE': 'Cash loans', 'CODE_GENDER': 'M', 'FLAG_OWN_CAR': 'N', 'FLAG_OWN_REALTY': 'Y', 'CNT_CHILDREN': 0, 'AMT_INCOME_TOTAL': 202500.0, 'AMT_CREDIT': 406597.5, 'AMT_ANNUITY': 24700.5, 'AMT_GOODS_PRICE': 351000.0, 'NAME_TYPE_SUITE': 'Unaccompanied', 'NAME_INCOME_TYPE': 'Working', 'NAME_EDUCATION_TYPE': 'Secondary / secondary special', 'NAME_FAMILY_STATUS': 'Single / not married', 'NAME_HOUSING_TYPE': 'House / apartment', 'REGION_POPULATION_RELATIVE': 0.018801, 'DAYS_BIRTH': -9461, 'DAYS_EMPLOYED': -637, 'DAYS_REGISTRATION': -3648.0, 'DAYS_ID_PUBLISH': -2120, 'OWN_CAR_AGE': 0.0, 'FLAG_MOBIL': 1, 'FLAG_EMP_PHONE': 1, 'FLAG_WORK_PHONE': 0, 'FLAG_CONT_MOBILE': 1, 'FLAG_PHONE': 1, 'FLAG_EMAIL': 0, 'OCCUPATION_TYPE': 'Laborers', 'CNT_FAM_MEMBERS': 1.0, 'REGION_RATING_CLIENT': 2, 'REGION_RATING_CLIENT_W_CITY': 2, 'WEEKDAY_APPR_PROCESS_START': 'WEDNESDAY', 'HOUR_APPR_PROCESS_START': 10, 'REG_REGION_NOT_LIVE_REGION': 0, 'REG_REGION_NOT_WORK_REGION': 0, 'LIVE_REGION_NOT_WORK_REGION': 0, 'REG_CITY_NOT_LIVE_CITY': 0, 'REG_CITY_NOT_WORK_CITY': 0, 'LIVE_CITY_NOT_WORK_CITY': 0, 'ORGANIZATION_TYPE': 'Business Entity Type 3', 'EXT_SOURCE_1': 0.0830369673913225, 'EXT_SOURCE_2': 0.2629485927471776, 'EXT_SOURCE_3': 0.1393757800997895, 'APARTMENTS_AVG': 0.0247, 'BASEMENTAREA_AVG': 0.0369, 'YEARS_BEGINEXPLUATATION_AVG': 0.9722, 'YEARS_BUILD_AVG': 0.6192, 'COMMONAREA_AVG': 0.0143, 'ELEVATORS_AVG': 0.0, 'ENTRANCES_AVG': 0.069, 'FLOORSMAX_AVG': 0.0833, 'FLOORSMIN_AVG': 0.125, 'LANDAREA_AVG': 0.0369, 'LIVINGAPARTMENTS_AVG': 0.0202, 'LIVINGAREA_AVG': 0.019, 'NONLIVINGAPARTMENTS_AVG': 0.0, 'NONLIVINGAREA_AVG': 0.0, 'APARTMENTS_MODE': 0.0252, 'BASEMENTAREA_MODE': 0.0383, 'YEARS_BEGINEXPLUATATION_MODE': 0.9722, 'YEARS_BUILD_MODE': 0.6341, 'COMMONAREA_MODE': 0.0144, 'ELEVATORS_MODE': 0.0, 'ENTRANCES_MODE': 0.069, 'FLOORSMAX_MODE': 0.0833, 'FLOORSMIN_MODE': 0.125, 'LANDAREA_MODE': 0.0377, 'LIVINGAPARTMENTS_MODE': 0.022, 'LIVINGAREA_MODE': 0.0198, 'NONLIVINGAPARTMENTS_MODE': 0.0, 'NONLIVINGAREA_MODE': 0.0, 'APARTMENTS_MEDI': 0.025, 'BASEMENTAREA_MEDI': 0.0369, 'YEARS_BEGINEXPLUATATION_MEDI': 0.9722, 'YEARS_BUILD_MEDI': 0.6243, 'COMMONAREA_MEDI': 0.0144, 'ELEVATORS_MEDI': 0.0, 'ENTRANCES_MEDI': 0.069, 'FLOORSMAX_MEDI': 0.0833, 'FLOORSMIN_MEDI': 0.125, 'LANDAREA_MEDI': 0.0375, 'LIVINGAPARTMENTS_MEDI': 0.0205, 'LIVINGAREA_MEDI': 0.0193, 'NONLIVINGAPARTMENTS_MEDI': 0.0, 'NONLIVINGAREA_MEDI': 0.0, 'FONDKAPREMONT_MODE': 'reg oper account', 'HOUSETYPE_MODE': 'block of flats', 'TOTALAREA_MODE': 0.0149, 'WALLSMATERIAL_MODE': 'Stone, brick', 'EMERGENCYSTATE_MODE': 'No', 'OBS_30_CNT_SOCIAL_CIRCLE': 2.0, 'DEF_30_CNT_SOCIAL_CIRCLE': 2.0, 'OBS_60_CNT_SOCIAL_CIRCLE': 2.0, 'DEF_60_CNT_SOCIAL_CIRCLE': 2.0, 'DAYS_LAST_PHONE_CHANGE': -1134.0, 'FLAG_DOCUMENT_2': 0, 'FLAG_DOCUMENT_3': 1, 'FLAG_DOCUMENT_4': 0, 'FLAG_DOCUMENT_5': 0, 'FLAG_DOCUMENT_6': 0, 'FLAG_DOCUMENT_7': 0, 'FLAG_DOCUMENT_8': 0, 'FLAG_DOCUMENT_9': 0, 'FLAG_DOCUMENT_10': 0, 'FLAG_DOCUMENT_11': 0, 'FLAG_DOCUMENT_12': 0, 'FLAG_DOCUMENT_13': 0, 'FLAG_DOCUMENT_14': 0, 'FLAG_DOCUMENT_15': 0, 'FLAG_DOCUMENT_16': 0, 'FLAG_DOCUMENT_17': 0, 'FLAG_DOCUMENT_18': 0, 'FLAG_DOCUMENT_19': 0, 'FLAG_DOCUMENT_20': 0, 'FLAG_DOCUMENT_21': 0, 'AMT_REQ_CREDIT_BUREAU_HOUR': 0.0, 'AMT_REQ_CREDIT_BUREAU_DAY': 0.0, 'AMT_REQ_CREDIT_BUREAU_WEEK': 0.0, 'AMT_REQ_CREDIT_BUREAU_MON': 0.0, 'AMT_REQ_CREDIT_BUREAU_QRT': 0.0, 'AMT_REQ_CREDIT_BUREAU_YEAR': 1.0, 'SK_ID_BUREAU_mean': 6153272.125, 'SK_ID_BUREAU_max': 6158909.0, 'SK_ID_BUREAU_min': 6113835.0, 'SK_ID_BUREAU_sum': 49226177.0, 'DAYS_CREDIT_mean': -874.0, 'DAYS_CREDIT_max': -103.0, 'DAYS_CREDIT_min': -1437.0, 'DAYS_CREDIT_sum': -6992.0, 'CREDIT_DAY_OVERDUE_mean': 0.0, 'CREDIT_DAY_OVERDUE_max': 0.0, 'CREDIT_DAY_OVERDUE_min': 0.0, 'CREDIT_DAY_OVERDUE_sum': 0.0, 'CNT_CREDIT_PROLONG_mean': 0.0, 'CNT_CREDIT_PROLONG_max': 0.0, 'CNT_CREDIT_PROLONG_min': 0.0, 'CNT_CREDIT_PROLONG_sum': 0.0, 'AMT_CREDIT_SUM_mean': 108131.945625, 'AMT_CREDIT_SUM_max': 450000.0, 'AMT_CREDIT_SUM_min': 0.0, 'AMT_CREDIT_SUM_sum': 865055.565, 'AMT_CREDIT_SUM_DEBT_mean': 49156.2, 'AMT_CREDIT_SUM_DEBT_max': 245781.0, 'AMT_CREDIT_SUM_DEBT_min': 0.0, 'AMT_CREDIT_SUM_DEBT_sum': 245781.0, 'AMT_CREDIT_SUM_LIMIT_mean': 7997.14125, 'AMT_CREDIT_SUM_LIMIT_max': 31988.565, 'AMT_CREDIT_SUM_LIMIT_min': 0.0, 'AMT_CREDIT_SUM_LIMIT_sum': 31988.565, 'AMT_CREDIT_SUM_OVERDUE_mean': 0.0, 'AMT_CREDIT_SUM_OVERDUE_max': 0.0, 'AMT_CREDIT_SUM_OVERDUE_min': 0.0, 'AMT_CREDIT_SUM_OVERDUE_sum': 0.0, 'AMT_APPLICATION_mean': 179055.0, 'AMT_APPLICATION_max': 179055.0, 'AMT_APPLICATION_min': 179055.0, 'AMT_APPLICATION_sum': 179055.0, 'AMT_CREDIT_mean': 179055.0, 'AMT_CREDIT_max': 179055.0, 'AMT_CREDIT_min': 179055.0, 'AMT_CREDIT_sum': 179055.0, 'CNT_PAYMENT_mean': 24.0, 'CNT_PAYMENT_max': 24.0, 'CNT_PAYMENT_min': 24.0, 'NFLAG_INSURED_ON_APPROVAL_sum': 0.0, 'NFLAG_INSURED_ON_APPROVAL_mean': 0.0, 'NAME_CONTRACT_TYPE_Consumer loans': 1.0, 'NAME_CONTRACT_TYPE_Revolving loans': 0.0, 'NAME_CONTRACT_TYPE_XNA': 0.0, 'NAME_YIELD_GROUP_high': 0.0, 'NAME_YIELD_GROUP_low_action': 0.0, 'NAME_YIELD_GROUP_low_normal': 1.0, 'NAME_YIELD_GROUP_middle': 0.0, 'PRODUCT_COMBINATION_Card X-Sell': 0.0, 'PRODUCT_COMBINATION_Cash': 0.0, 'PRODUCT_COMBINATION_Cash Street: high': 0.0, 'PRODUCT_COMBINATION_Cash Street: low': 0.0, 'PRODUCT_COMBINATION_Cash Street: middle': 0.0, 'PRODUCT_COMBINATION_Cash X-Sell: high': 0.0, 'PRODUCT_COMBINATION_Cash X-Sell: low': 0.0, 'PRODUCT_COMBINATION_Cash X-Sell: middle': 0.0, 'PRODUCT_COMBINATION_POS household with interest': 0.0, 'PRODUCT_COMBINATION_POS household without interest': 0.0, 'PRODUCT_COMBINATION_POS industry with interest': 0.0, 'PRODUCT_COMBINATION_POS industry without interest': 0.0, 'PRODUCT_COMBINATION_POS mobile with interest': 0.0, 'PRODUCT_COMBINATION_POS mobile without interest': 0.0, 'PRODUCT_COMBINATION_POS other with interest': 1.0, 'PRODUCT_COMBINATION_POS others without interest': 0.0, 'PRODUCT_COMBINATION_nan': 0.0, 'INST_AMT_INSTALMENT_MEAN': 11559.247105263159, 'INST_AMT_INSTALMENT_MAX': 53093.745, 'INST_AMT_INSTALMENT_SUM': 219625.695, 'INST_AMT_PAYMENT_MEAN': 11559.247105263159, 'INST_AMT_PAYMENT_MAX': 53093.745, 'INST_AMT_PAYMENT_SUM': 219625.695, 'INST_PAYMENT_RATIO_MEAN': 0.99999999989661, 'INST_PAYMENT_RATIO_MAX': 0.9999999999811654, 'INST_PAYMENT_RATIO_MIN': 0.9999999998919126, 'INST_SK_ID_PREV_NUNIQUE': 1.0, 'INST_NUM_INSTALMENT_NUMBER_MAX': 19.0, 'CC_MONTHS_BALANCE_MEAN': 0.0, 'CC_MONTHS_BALANCE_MAX': 0.0, 'CC_MONTHS_BALANCE_MIN': 0.0, 'CC_MONTHS_BALANCE_SUM': 0.0, 'CC_AMT_BALANCE_MEAN': 0.0, 'CC_AMT_BALANCE_MAX': 0.0, 'CC_AMT_BALANCE_MIN': 0.0, 'CC_AMT_BALANCE_SUM': 0.0, 'CC_AMT_CREDIT_LIMIT_ACTUAL_MEAN': 0.0, 'CC_AMT_CREDIT_LIMIT_ACTUAL_MAX': 0.0, 'CC_AMT_CREDIT_LIMIT_ACTUAL_MIN': 0.0, 'CC_AMT_CREDIT_LIMIT_ACTUAL_SUM': 0.0, 'CC_AMT_DRAWINGS_ATM_CURRENT_MEAN': 0.0, 'CC_AMT_DRAWINGS_ATM_CURRENT_MAX': 0.0, 'CC_AMT_DRAWINGS_ATM_CURRENT_MIN': 0.0, 'CC_AMT_DRAWINGS_ATM_CURRENT_SUM': 0.0, 'CC_AMT_DRAWINGS_CURRENT_MEAN': 0.0, 'CC_AMT_DRAWINGS_CURRENT_MAX': 0.0, 'CC_AMT_DRAWINGS_CURRENT_MIN': 0.0, 'CC_AMT_DRAWINGS_CURRENT_SUM': 0.0, 'CC_AMT_DRAWINGS_OTHER_CURRENT_MEAN': 0.0, 'CC_AMT_DRAWINGS_OTHER_CURRENT_MAX': 0.0, 'CC_AMT_DRAWINGS_OTHER_CURRENT_MIN': 0.0, 'CC_AMT_DRAWINGS_OTHER_CURRENT_SUM': 0.0, 'CC_AMT_DRAWINGS_POS_CURRENT_MEAN': 0.0, 'CC_AMT_DRAWINGS_POS_CURRENT_MAX': 0.0, 'CC_AMT_DRAWINGS_POS_CURRENT_MIN': 0.0, 'CC_AMT_DRAWINGS_POS_CURRENT_SUM': 0.0, 'CC_AMT_INST_MIN_REGULARITY_MEAN': 0.0, 'CC_AMT_INST_MIN_REGULARITY_MAX': 0.0, 'CC_AMT_INST_MIN_REGULARITY_MIN': 0.0, 'CC_AMT_INST_MIN_REGULARITY_SUM': 0.0, 'CC_AMT_PAYMENT_CURRENT_MEAN': 0.0, 'CC_AMT_PAYMENT_CURRENT_MAX': 0.0, 'CC_AMT_PAYMENT_CURRENT_MIN': 0.0, 'CC_AMT_PAYMENT_CURRENT_SUM': 0.0, 'CC_AMT_PAYMENT_TOTAL_CURRENT_MEAN': 0.0, 'CC_AMT_PAYMENT_TOTAL_CURRENT_MAX': 0.0, 'CC_AMT_PAYMENT_TOTAL_CURRENT_MIN': 0.0, 'CC_AMT_PAYMENT_TOTAL_CURRENT_SUM': 0.0, 'CC_AMT_RECEIVABLE_PRINCIPAL_MEAN': 0.0, 'CC_AMT_RECEIVABLE_PRINCIPAL_MAX': 0.0, 'CC_AMT_RECEIVABLE_PRINCIPAL_MIN': 0.0, 'CC_AMT_RECEIVABLE_PRINCIPAL_SUM': 0.0, 'CC_AMT_RECIVABLE_MEAN': 0.0, 'CC_AMT_RECIVABLE_MAX': 0.0, 'CC_AMT_RECIVABLE_MIN': 0.0, 'CC_AMT_RECIVABLE_SUM': 0.0, 'CC_AMT_TOTAL_RECEIVABLE_MEAN': 0.0, 'CC_AMT_TOTAL_RECEIVABLE_MAX': 0.0, 'CC_AMT_TOTAL_RECEIVABLE_MIN': 0.0, 'CC_AMT_TOTAL_RECEIVABLE_SUM': 0.0, 'CC_CNT_DRAWINGS_ATM_CURRENT_MEAN': 0.0, 'CC_CNT_DRAWINGS_ATM_CURRENT_MAX': 0.0, 'CC_CNT_DRAWINGS_ATM_CURRENT_MIN': 0.0, 'CC_CNT_DRAWINGS_ATM_CURRENT_SUM': 0.0, 'CC_CNT_DRAWINGS_CURRENT_MEAN': 0.0, 'CC_CNT_DRAWINGS_CURRENT_MAX': 0.0, 'CC_CNT_DRAWINGS_CURRENT_MIN': 0.0, 'CC_CNT_DRAWINGS_CURRENT_SUM': 0.0, 'CC_CNT_DRAWINGS_OTHER_CURRENT_MEAN': 0.0, 'CC_CNT_DRAWINGS_OTHER_CURRENT_MAX': 0.0, 'CC_CNT_DRAWINGS_OTHER_CURRENT_MIN': 0.0, 'CC_CNT_DRAWINGS_OTHER_CURRENT_SUM': 0.0, 'CC_CNT_DRAWINGS_POS_CURRENT_MEAN': 0.0, 'CC_CNT_DRAWINGS_POS_CURRENT_MAX': 0.0, 'CC_CNT_DRAWINGS_POS_CURRENT_MIN': 0.0, 'CC_CNT_DRAWINGS_POS_CURRENT_SUM': 0.0, 'CC_CNT_INSTALMENT_MATURE_CUM_MEAN': 0.0, 'CC_CNT_INSTALMENT_MATURE_CUM_MAX': 0.0, 'CC_CNT_INSTALMENT_MATURE_CUM_MIN': 0.0, 'CC_CNT_INSTALMENT_MATURE_CUM_SUM': 0.0, 'CC_SK_DPD_MEAN': 0.0, 'CC_SK_DPD_MAX': 0.0, 'CC_SK_DPD_MIN': 0.0, 'CC_SK_DPD_SUM': 0.0, 'CC_SK_DPD_DEF_MEAN': 0.0, 'CC_SK_DPD_DEF_MAX': 0.0, 'CC_SK_DPD_DEF_MIN': 0.0, 'CC_SK_DPD_DEF_SUM': 0.0, 'POS_MONTHS_BALANCE_MEAN': -10.0, 'POS_MONTHS_BALANCE_MAX': -1.0, 'POS_MONTHS_BALANCE_MIN': -19.0, 'POS_MONTHS_BALANCE_SUM': -190.0, 'POS_CNT_INSTALMENT_MEAN': 24.0, 'POS_CNT_INSTALMENT_MAX': 24.0, 'POS_CNT_INSTALMENT_MIN': 24.0, 'POS_CNT_INSTALMENT_SUM': 456.0, 'POS_CNT_INSTALMENT_FUTURE_MEAN': 15.0, 'POS_CNT_INSTALMENT_FUTURE_MAX': 24.0, 'POS_CNT_INSTALMENT_FUTURE_MIN': 6.0, 'POS_CNT_INSTALMENT_FUTURE_SUM': 285.0, 'POS_SK_DPD_MEAN': 0.0, 'POS_SK_DPD_MAX': 0.0, 'POS_SK_DPD_MIN': 0.0, 'POS_SK_DPD_SUM': 0.0, 'POS_SK_DPD_DEF_MEAN': 0.0, 'POS_SK_DPD_DEF_MAX': 0.0, 'POS_SK_DPD_DEF_MIN': 0.0, 'POS_SK_DPD_DEF_SUM': 0.0}



    result = predict(model_type="rf", raw_input_dict=sample_input)
    print("✅ Prediction:", result)
